# 기본 환경 선택
spring:
  profiles:
    active: local # 기본 환경 선택
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8090
myConfig:
  joinParameterKey: 'AEa#&9$+VV.HNUTz'
#local 환경
---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    password: ''
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:mysql://34.64.79.129:3306/cojamDB?useUnicode=true&useSSL=false&serverTimezone=UTC&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: cojam
    password: '@2cojam'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: 'cojam.limited@gmail.com'
    password: 'YFCqZ1KWya85NpXf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    io.cojam.web: debug
myConfig:
  uploadPath: "/Users/jaeheonjung/PROJECT/localUpload/cojam"
  hostUrl: "http://localhost:8090"
  klaytnScpe: "https://baobab.scope.klaytn.com/"
app:
  name: hiblocks-internal
  adminToken: RfLS97hYHH9F7WmmFmv5HDWJYUTVGLrkJJEYWChx
  cache:
    specs:
      token-price:
        timeout: 60
  klaytn:
    contracts:
      marketAddress: 0xb74d4E4b3a89137057DD886a34A6541D1986a916
  sdk-enclave:
    apiSecret: "iXh3eCTk9ehUZgpus4U7ZL0itORivfHnDGeRjy4oGUs="
    accessToken: "eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImNvamFtX2xpbWl0ZWRAbmF2ZXIuY29tIiwiaWQiOiI2Nzg0ZDM1YzU2ZDBiNDc2Y2I0MGU4NDhiNGQzODdhZCIsInR5cGUiOiJMT05HIiwibG9uZ1R5cGUiOnRydWUsImlzcyI6ImhlbmVzaXMtd2FsbGV0LWlkZW50aXR5LXByb2QtdGVzdG5ldCIsImlhdCI6MTYyMjA4NDkyMywiZXhwIjozMTY5ODIwODQ5MjN9.e3vwbds3pZKgw_cK9whmZ0y73JDcDyiCJZ_OH7MiSyKG2sOb0Whb-dpTrSGpEe3L3m8d83Lr5wE5heN1dGXdoQ"
    masterWalletId: "d24c99e81a62b7aaf85cfc1134e1c1ae"
    masterWalletAddress: "0x4a1667cf934796067adbddf456c95ef91658b403"
    marketAddress: "0xb74d4E4b3a89137057DD886a34A6541D1986a916"
    tokenAddress: "0xd6cdab407f47afaa8800af5006061db8dc92aae7"
    feeAddress: "0x6b35e1a72f97320945789b3e7c6a203de1c4f0d3"
    charityAddress: "0xe3469be62a72988a5462c413aef4d6efd59fff3d"
    remainAddress: "0x4a1667cf934796067adbddf456c95ef91658b403"
    recommendWalletId: "0c109712c239534be85bdeacc4ef1cd0"
    recommendAddress: "0xd3b63ca1215a9f13d38e3a782672cda6ae098e40"
    recommendPassphrase: "!1wjdwogjs"
    passphrase: "!1wjdwogjs"
    url: http://localhost:3000
#개발 환경
---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: localhost
    port: 6379
    password: ''
    timeout: 0
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:mysql://34.64.180.205:3306/cojamDB?useUnicode=true&serverTimezone=UTC&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: cojam
    password: '@2cojam'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: 'cojam.limited@gmail.com'
    password: 'YFCqZ1KWya85NpXf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    io.cojam.web: debug
myConfig:
  uploadPath: "/cojam_data/web_upload"
  hostUrl: "http://dev.cojam.io"
  klaytnScpe: "https://baobab.scope.klaytn.com/"
app:
  name: hiblocks-internal
  adminToken: RfLS97hYHH9F7WmmFmv5HDWJYUTVGLrkJJEYWChx
  cache:
    specs:
      token-price:
        timeout: 60
  klaytn:
    contracts:
      marketAddress: 0x3B319E5Ce59603fdFa3039b5991054E6d8191B4C
  sdk-enclave:
    apiSecret: "iXh3eCTk9ehUZgpus4U7ZL0itORivfHnDGeRjy4oGUs="
    accessToken: "eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImNvamFtX2xpbWl0ZWRAbmF2ZXIuY29tIiwiaWQiOiI2Nzg0ZDM1YzU2ZDBiNDc2Y2I0MGU4NDhiNGQzODdhZCIsInR5cGUiOiJMT05HIiwibG9uZ1R5cGUiOnRydWUsImlzcyI6ImhlbmVzaXMtd2FsbGV0LWlkZW50aXR5LXByb2QtdGVzdG5ldCIsImlhdCI6MTYyMjA4NDkyMywiZXhwIjozMTY5ODIwODQ5MjN9.e3vwbds3pZKgw_cK9whmZ0y73JDcDyiCJZ_OH7MiSyKG2sOb0Whb-dpTrSGpEe3L3m8d83Lr5wE5heN1dGXdoQ"
    masterWalletId: "d24c99e81a62b7aaf85cfc1134e1c1ae"
    masterWalletAddress: "0x4a1667cf934796067adbddf456c95ef91658b403"
    marketAddress: "0x03aD3578F4eF3a2d414CB28aeBBb58F0716b4D62"
    tokenAddress: "0xd6cdab407f47afaa8800af5006061db8dc92aae7"
    feeAddress: "0x6b35e1a72f97320945789b3e7c6a203de1c4f0d3"
    charityAddress: "0xe3469be62a72988a5462c413aef4d6efd59fff3d"
    remainAddress: "0x4a1667cf934796067adbddf456c95ef91658b403"
    recommendWalletId: "0c109712c239534be85bdeacc4ef1cd0"
    recommendAddress: "0xd3b63ca1215a9f13d38e3a782672cda6ae098e40"
    recommendPassphrase: "!1wjdwogjs"
    passphrase: "!1wjdwogjs"
    url: http://localhost:3000
#운영 환경
---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: localhost
    port: 6379
    password: ''
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:mysql://10.42.80.2:3306/cojamDB?useUnicode=true&useSSL=false&serverTimezone=UTC&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: cojam
    password: '@2cojam'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 150
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
    tomcat:
      max-idle:
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: 'cojam.limited@gmail.com'
    password: 'YFCqZ1KWya85NpXf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    io.cojam.web: error
myConfig:
  uploadPath: "/cojam_data/upload"
  hostUrl: "https://www.cojam.io"
  klaytnScpe: "https://scope.klaytn.com/"
app:
  name: hiblocks-internal
  adminToken: RfLS97hYHH9F7WmmFmv5HDWJYUTVGLrkJJEYWChx
  cache:
    specs:
      token-price:
        timeout: 60
  klaytn:
    contracts:
      marketAddress: "0x8Ab95fAb0c6F038312E14eC08461b008E03Eda0d"
  sdk-enclave:
    apiSecret: "5cs80y8woXhe+BpU67T8NCFh1VfALyeSz5VJQxCX6C8="
    accessToken: "eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6InN1cHBvcnRAY29qYW0uaW8iLCJpZCI6ImVjNDM5MWFhZjcwYWU2NjcyNzE3Mzg2NGRiOWVlM2QyIiwidHlwZSI6IkxPTkciLCJsb25nVHlwZSI6dHJ1ZSwiaXNzIjoiaGVuZXNpcy13YWxsZXQtaWRlbnRpdHktcHJvZC1tYWlubmV0IiwiaWF0IjoxNjE5NTA5NDg1LCJleHAiOjE2NTEwNDU0ODV9.6Op6kCkhqaeg2MZG7g9G2xjPvz_AMdMBWMnPVToEL8dn9WUJLvA2336gQboqA-ZGWqz9hHLIF-HoX2r_7vtZ8g"
    masterWalletId: "bdebedc64f25ac3a343d15a376dcc0a0"
    masterWalletAddress: "0x281650e1270265dde07ae465d179eb560132eafa"
    marketAddress: "0x8Ab95fAb0c6F038312E14eC08461b008E03Eda0d"
    tokenAddress: "0x7f223b1607171b81ebd68d22f1ca79157fd4a44b"
    feeAddress: "0x24a0f37edb290010e4b15597d17581e439505606"
    charityAddress: "0x946de569a7d041b56c98306b3c06d8dfd04e78ae"
    remainAddress: "0x24a0f37edb290010e4b15597d17581e439505606"
    recommendWalletId: "7ec48453b5ae0b72122870c18e3577b8"
    recommendAddress: "0xfb193104052446709612d410a030227da96d08b2"
    recommendPassphrase: "Cojam2029@"
    passphrase: "Cojam2021@"
    url: http://localhost:3000